version: 2.1

executors:
  golang: 
    docker:
      - image: circleci/golang:1.11

jobs:
  test:
    executor: golang
    environment:
      TEST_REPORTS: /tmp/test-reports
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo apt-get -y install libusb-1.0-0-dev
            mkdir -p ${TEST_REPORTS}
            mkdir -p /go/pkg/mod
            [[ -e /go/bin/gotestsum ]] && exit
            curl -sSL https://github.com/gotestyourself/gotestsum/releases/download/v0.3.2/gotestsum_0.3.2_linux_amd64.tar.gz | \
              tar -xz -C /go/bin gotestsum

      - run:
          name: Hydrate credentials
          command: |
            mkdir -p ~/.studio-light/gcal
            echo ${CREDS_64} | base64 --decode > ~/.studio-light/gcal/credentials.json
            echo ${TOKEN_64} | base64 --decode > ~/.studio-light/gcal/token.json

      - run:
          name: Test
          environment:
            GOTESTSUM_JUNITFILE: /tmp/test-reports/go-test-report.xml
          command: |
            gotestsum -- -race -tags="integration" ./...

      - store_artifacts:
          path: /tmp/test-reports
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-reports

  
  lint:
    executor: golang
    steps:
      - checkout
      - run:
          name: Install
          command: |
            sudo apt-get -y install libusb-1.0-0-dev
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.12.5
      - run: |
          export PATH=$PATH:./bin
          mkdir -p /go/pkg/mod
          go mod download
          golangci-lint run
  
  arm:
    executor: golang
    steps:
      - checkout
      - run:
          name: Install
          command: |
            sudo apt-get -y install libusb-1.0-0-dev
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.12.5
      - run: |
          export PATH=$PATH:./bin
          mkdir -p /go/pkg/mod
          go mod download
          GOOS=linux CGO_LDFLAGS_ALLOW='-fconstant-cfstrings' go build
      - store_artifacts:
          path: blync-studio-light
      
        

workflows:
  version: 2
  workflow:
    jobs:
      - arm
      - test
      - lint